spring.application.name=apiHospital

# Banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Marinalva2495
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Servidor - porta 8080 (padrão)
server.port=8080

# Permitir binding em todas as interfaces (necessário para o app acessar via IP da rede)
server.address=0.0.0.0
